version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pytest
      - pycodestyle cryptopals/
      - aws --version
      - REPOSITORY_URI=698202155810.dkr.ecr.us-east-2.amazonaws.com/cryptopals
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - service docker start
      - apt-get update
      - apt-get install docker
      - $(aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $REPOSITORY_URI)
  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG


